# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthWechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=32, unique=True)),
                ('access_token', models.CharField(max_length=128)),
                ('refresh_token', models.CharField(max_length=128)),
                ('expire_ts', models.IntegerField(verbose_name='到期时间戳')),
                ('nick_name', models.CharField(max_length=64, verbose_name='昵称')),
                ('head_img', models.CharField(max_length=256, verbose_name='头像')),
                ('user_name', models.CharField(max_length=64, verbose_name='原始ID')),
                ('principal_name', models.CharField(max_length=64, verbose_name='主体名称')),
                ('qrcode_url', models.CharField(max_length=256, verbose_name='二维码链接')),
            ],
        ),
    ]
